version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
  disable:
    - depguard
  settings:
    errcheck:
      check-blank: false
      disable-default-exclusions: false
      exclude-functions:
        - (io.Closer).Close
        - (*database/sql.Rows).Close
        - (*os.File).Close
        - (net/http.ResponseWriter).Write
        - (*encoding/json.Encoder).Encode
        - os.Remove
  exclusions:
    paths:
      - frontend
      - docs
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - source: "defer "
        linters:
          - errcheck
