run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
  disable:
    - depguard

issues:
  exclude-dirs:
    - frontend
    - docs
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
