// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';
import {server} from '../models';
import {chat} from '../models';
import {observability} from '../models';
import {version} from '../models';
import {voice} from '../models';

export function CompleteLogin(arg1:string,arg2:number):Promise<auth.AuthState>;

export function CreateChannel(arg1:string,arg2:string,arg3:string,arg4:string):Promise<server.Channel>;

export function CreateServer(arg1:string,arg2:string):Promise<server.Server>;

export function DeleteChannel(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteMessage(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteServer(arg1:string,arg2:string):Promise<void>;

export function EditMessage(arg1:string,arg2:string,arg3:string):Promise<chat.Message>;

export function GenerateInvite(arg1:string,arg2:string):Promise<string>;

export function GetHealth():Promise<observability.Health>;

export function GetInviteInfo(arg1:string):Promise<server.InviteInfo>;

export function GetMessages(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<chat.Message>>;

export function GetServer(arg1:string):Promise<server.Server>;

export function GetVersion():Promise<version.Info>;

export function GetVoiceStatus():Promise<voice.VoiceStatus>;

export function Greet(arg1:string):Promise<string>;

export function JoinVoice(arg1:string):Promise<void>;

export function KickMember(arg1:string,arg2:string,arg3:string):Promise<void>;

export function LeaveVoice():Promise<void>;

export function ListChannels(arg1:string):Promise<Array<server.Channel>>;

export function ListMembers(arg1:string):Promise<Array<server.Member>>;

export function ListUserServers(arg1:string):Promise<Array<server.Server>>;

export function Logout(arg1:string):Promise<void>;

export function RedeemInvite(arg1:string,arg2:string):Promise<server.Server>;

export function RestoreSession(arg1:string):Promise<auth.AuthState>;

export function SearchMessages(arg1:string,arg2:string,arg3:number):Promise<Array<chat.SearchResult>>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<chat.Message>;

export function StartLogin():Promise<auth.DeviceCodeResponse>;

export function ToggleDeafen():Promise<boolean>;

export function ToggleMute():Promise<boolean>;

export function UpdateMemberRole(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateServer(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
