// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptFriendRequest(arg1, arg2) {
  return window['go']['main']['App']['AcceptFriendRequest'](arg1, arg2);
}

export function ApplyAutoUpdate(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyAutoUpdate'](arg1, arg2, arg3);
}

export function BlockUser(arg1, arg2) {
  return window['go']['main']['App']['BlockUser'](arg1, arg2);
}

export function CompleteLogin(arg1, arg2) {
  return window['go']['main']['App']['CompleteLogin'](arg1, arg2);
}

export function CreateChannel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateChannel'](arg1, arg2, arg3, arg4);
}

export function CreateServer(arg1, arg2) {
  return window['go']['main']['App']['CreateServer'](arg1, arg2);
}

export function DeleteAttachment(arg1) {
  return window['go']['main']['App']['DeleteAttachment'](arg1);
}

export function DeleteChannel(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteChannel'](arg1, arg2, arg3);
}

export function DeleteMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteMessage'](arg1, arg2, arg3);
}

export function DeleteServer(arg1, arg2) {
  return window['go']['main']['App']['DeleteServer'](arg1, arg2);
}

export function DisableTranslation() {
  return window['go']['main']['App']['DisableTranslation']();
}

export function DisableVoiceTranslation() {
  return window['go']['main']['App']['DisableVoiceTranslation']();
}

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function EditMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditMessage'](arg1, arg2, arg3);
}

export function EnableTranslation(arg1, arg2) {
  return window['go']['main']['App']['EnableTranslation'](arg1, arg2);
}

export function EnableVoiceTranslation(arg1, arg2) {
  return window['go']['main']['App']['EnableVoiceTranslation'](arg1, arg2);
}

export function GenerateInvite(arg1, arg2) {
  return window['go']['main']['App']['GenerateInvite'](arg1, arg2);
}

export function GetAttachments(arg1) {
  return window['go']['main']['App']['GetAttachments'](arg1);
}

export function GetFriends(arg1) {
  return window['go']['main']['App']['GetFriends'](arg1);
}

export function GetHealth() {
  return window['go']['main']['App']['GetHealth']();
}

export function GetInviteInfo(arg1) {
  return window['go']['main']['App']['GetInviteInfo'](arg1);
}

export function GetMessages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2, arg3, arg4);
}

export function GetP2PMessages(arg1, arg2) {
  return window['go']['main']['App']['GetP2PMessages'](arg1, arg2);
}

export function GetP2PPeerName(arg1) {
  return window['go']['main']['App']['GetP2PPeerName'](arg1);
}

export function GetP2PPeers() {
  return window['go']['main']['App']['GetP2PPeers']();
}

export function GetP2PRoomCode() {
  return window['go']['main']['App']['GetP2PRoomCode']();
}

export function GetPendingRequests(arg1) {
  return window['go']['main']['App']['GetPendingRequests'](arg1);
}

export function GetPublicURL() {
  return window['go']['main']['App']['GetPublicURL']();
}

export function GetServer(arg1) {
  return window['go']['main']['App']['GetServer'](arg1);
}

export function GetTranslationStatus() {
  return window['go']['main']['App']['GetTranslationStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetVoiceParticipants(arg1, arg2) {
  return window['go']['main']['App']['GetVoiceParticipants'](arg1, arg2);
}

export function GetVoiceStatus() {
  return window['go']['main']['App']['GetVoiceStatus']();
}

export function GetVoiceTranslationStatus() {
  return window['go']['main']['App']['GetVoiceTranslationStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitP2PHost() {
  return window['go']['main']['App']['InitP2PHost']();
}

export function JoinP2PRoom(arg1) {
  return window['go']['main']['App']['JoinP2PRoom'](arg1);
}

export function JoinVoice(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['JoinVoice'](arg1, arg2, arg3, arg4, arg5);
}

export function JoinVoiceWithURL(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['JoinVoiceWithURL'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function KickMember(arg1, arg2, arg3) {
  return window['go']['main']['App']['KickMember'](arg1, arg2, arg3);
}

export function LeaveVoice() {
  return window['go']['main']['App']['LeaveVoice']();
}

export function ListChannels(arg1) {
  return window['go']['main']['App']['ListChannels'](arg1);
}

export function ListMembers(arg1) {
  return window['go']['main']['App']['ListMembers'](arg1);
}

export function ListUserServers(arg1) {
  return window['go']['main']['App']['ListUserServers'](arg1);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function RedeemInvite(arg1, arg2) {
  return window['go']['main']['App']['RedeemInvite'](arg1, arg2);
}

export function RejectFriendRequest(arg1, arg2) {
  return window['go']['main']['App']['RejectFriendRequest'](arg1, arg2);
}

export function RemoveFriend(arg1, arg2) {
  return window['go']['main']['App']['RemoveFriend'](arg1, arg2);
}

export function RestoreSession(arg1) {
  return window['go']['main']['App']['RestoreSession'](arg1);
}

export function SearchMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchMessages'](arg1, arg2, arg3);
}

export function SelectAvatarFile() {
  return window['go']['main']['App']['SelectAvatarFile']();
}

export function SendFriendRequest(arg1, arg2) {
  return window['go']['main']['App']['SendFriendRequest'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SendP2PMessage(arg1, arg2) {
  return window['go']['main']['App']['SendP2PMessage'](arg1, arg2);
}

export function SendP2PProfile(arg1, arg2) {
  return window['go']['main']['App']['SendP2PProfile'](arg1, arg2);
}

export function StartLogin() {
  return window['go']['main']['App']['StartLogin']();
}

export function ToggleDeafen() {
  return window['go']['main']['App']['ToggleDeafen']();
}

export function ToggleMute() {
  return window['go']['main']['App']['ToggleMute']();
}

export function TranslateText(arg1, arg2, arg3) {
  return window['go']['main']['App']['TranslateText'](arg1, arg2, arg3);
}

export function UnblockUser(arg1, arg2) {
  return window['go']['main']['App']['UnblockUser'](arg1, arg2);
}

export function UpdateMemberRole(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateMemberRole'](arg1, arg2, arg3, arg4);
}

export function UpdateServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateServer'](arg1, arg2, arg3, arg4);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3);
}
