// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteLogin(arg1, arg2) {
  return window['go']['main']['App']['CompleteLogin'](arg1, arg2);
}

export function CreateChannel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateChannel'](arg1, arg2, arg3, arg4);
}

export function CreateServer(arg1, arg2) {
  return window['go']['main']['App']['CreateServer'](arg1, arg2);
}

export function DeleteAttachment(arg1) {
  return window['go']['main']['App']['DeleteAttachment'](arg1);
}

export function DeleteChannel(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteChannel'](arg1, arg2, arg3);
}

export function DeleteMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteMessage'](arg1, arg2, arg3);
}

export function DeleteServer(arg1, arg2) {
  return window['go']['main']['App']['DeleteServer'](arg1, arg2);
}

export function DisableTranslation() {
  return window['go']['main']['App']['DisableTranslation']();
}

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function EditMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditMessage'](arg1, arg2, arg3);
}

export function EnableTranslation(arg1, arg2) {
  return window['go']['main']['App']['EnableTranslation'](arg1, arg2);
}

export function GenerateInvite(arg1, arg2) {
  return window['go']['main']['App']['GenerateInvite'](arg1, arg2);
}

export function GetAttachments(arg1) {
  return window['go']['main']['App']['GetAttachments'](arg1);
}

export function GetHealth() {
  return window['go']['main']['App']['GetHealth']();
}

export function GetInviteInfo(arg1) {
  return window['go']['main']['App']['GetInviteInfo'](arg1);
}

export function GetMessages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2, arg3, arg4);
}

export function GetServer(arg1) {
  return window['go']['main']['App']['GetServer'](arg1);
}

export function GetTranslationStatus() {
  return window['go']['main']['App']['GetTranslationStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetVoiceStatus() {
  return window['go']['main']['App']['GetVoiceStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function JoinVoice(arg1) {
  return window['go']['main']['App']['JoinVoice'](arg1);
}

export function KickMember(arg1, arg2, arg3) {
  return window['go']['main']['App']['KickMember'](arg1, arg2, arg3);
}

export function LeaveVoice() {
  return window['go']['main']['App']['LeaveVoice']();
}

export function ListChannels(arg1) {
  return window['go']['main']['App']['ListChannels'](arg1);
}

export function ListMembers(arg1) {
  return window['go']['main']['App']['ListMembers'](arg1);
}

export function ListUserServers(arg1) {
  return window['go']['main']['App']['ListUserServers'](arg1);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function RedeemInvite(arg1, arg2) {
  return window['go']['main']['App']['RedeemInvite'](arg1, arg2);
}

export function RestoreSession(arg1) {
  return window['go']['main']['App']['RestoreSession'](arg1);
}

export function SearchMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchMessages'](arg1, arg2, arg3);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function StartLogin() {
  return window['go']['main']['App']['StartLogin']();
}

export function ToggleDeafen() {
  return window['go']['main']['App']['ToggleDeafen']();
}

export function ToggleMute() {
  return window['go']['main']['App']['ToggleMute']();
}

export function UpdateMemberRole(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateMemberRole'](arg1, arg2, arg3, arg4);
}

export function UpdateServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateServer'](arg1, arg2, arg3, arg4);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3);
}
